import { Report } from "@/types/report";

export const mockReports: Report[] = [
    {
        id: "rpt-001",
        disease: "Leaf Blight",
        confidence: 0.91,
        severity: "Moderate",
        treatment: "Apply copper-based fungicide (Bordeaux mixture) within 48 hours. Ensure thorough coverage on both leaf surfaces.",
        follow_up: "Re-scan affected area after 5 days to monitor disease progression.",
        date: "2026-02-28",
        cropType: "Rice",
        imageUrl: "/images/leaf-blight.jpg",
        preventiveMeasures: [
            "Ensure proper spacing between plants for air circulation",
            "Avoid overhead irrigation to reduce leaf wetness",
            "Remove and destroy infected plant debris",
            "Use disease-resistant crop varieties",
        ],
        timeline: [
            { date: "2026-02-28", action: "Disease detected via AI scan", status: "completed" },
            { date: "2026-02-28", action: "Apply copper fungicide", status: "pending" },
            { date: "2026-03-05", action: "Follow-up scan", status: "upcoming" },
            { date: "2026-03-10", action: "Second treatment if needed", status: "upcoming" },
        ],
    },
    {
        id: "rpt-002",
        disease: "Powdery Mildew",
        confidence: 0.87,
        severity: "Low",
        treatment: "Apply sulfur-based fungicide or neem oil spray. Treat during early morning or late evening.",
        follow_up: "Monitor weekly. Re-apply treatment if symptoms persist after 7 days.",
        date: "2026-02-26",
        cropType: "Wheat",
        imageUrl: "/images/powdery-mildew.jpg",
        preventiveMeasures: [
            "Improve air circulation around plants",
            "Avoid excessive nitrogen fertilization",
            "Water at the base of plants, not on foliage",
        ],
        timeline: [
            { date: "2026-02-26", action: "Initial AI scan and diagnosis", status: "completed" },
            { date: "2026-02-27", action: "Applied neem oil treatment", status: "completed" },
            { date: "2026-03-03", action: "Follow-up inspection", status: "upcoming" },
        ],
    },
    {
        id: "rpt-003",
        disease: "Late Blight",
        confidence: 0.95,
        severity: "Severe",
        treatment: "Immediately apply systemic fungicide (Metalaxyl + Mancozeb). Isolate affected area to prevent spread.",
        follow_up: "Urgent re-scan in 3 days. Consider crop removal if disease spreads beyond 40% coverage.",
        date: "2026-02-24",
        cropType: "Tomato",
        imageUrl: "/images/late-blight.jpg",
        preventiveMeasures: [
            "Use certified disease-free seeds and transplants",
            "Apply preventive fungicide before rainy season",
            "Destroy all infected plants immediately",
            "Rotate crops every season",
            "Ensure proper drainage in field",
        ],
        timeline: [
            { date: "2026-02-24", action: "Severe infection detected", status: "completed" },
            { date: "2026-02-24", action: "Emergency fungicide applied", status: "completed" },
            { date: "2026-02-25", action: "Infected area isolated", status: "completed" },
            { date: "2026-02-27", action: "Follow-up scan", status: "pending" },
            { date: "2026-03-01", action: "Assess treatment efficacy", status: "upcoming" },
        ],
    },
    {
        id: "rpt-004",
        disease: "Bacterial Leaf Spot",
        confidence: 0.78,
        severity: "Moderate",
        treatment: "Apply copper hydroxide spray. Remove severely affected leaves to reduce inoculum.",
        follow_up: "Re-scan after 7 days. Adjust treatment if new spots appear.",
        date: "2026-02-20",
        cropType: "Bell Pepper",
        imageUrl: "/images/bacterial-spot.jpg",
        preventiveMeasures: [
            "Use pathogen-free seeds",
            "Practice crop rotation with non-host crops",
            "Avoid working in fields when foliage is wet",
        ],
        timeline: [
            { date: "2026-02-20", action: "Disease identified", status: "completed" },
            { date: "2026-02-21", action: "Copper hydroxide treatment", status: "completed" },
            { date: "2026-02-27", action: "Re-scan scheduled", status: "upcoming" },
        ],
    },
    {
        id: "rpt-005",
        disease: "Rust Disease",
        confidence: 0.83,
        severity: "Low",
        treatment: "Apply triazole fungicide. Ensure complete coverage of stems and undersides of leaves.",
        follow_up: "Monitor every 5 days. If rust pustules increase, apply second treatment.",
        date: "2026-02-18",
        cropType: "Soybean",
        imageUrl: "/images/rust.jpg",
        preventiveMeasures: [
            "Plant rust-resistant varieties",
            "Maintain proper field hygiene",
            "Apply preventive fungicide at early growth stages",
        ],
        timeline: [
            { date: "2026-02-18", action: "Rust detected on leaves", status: "completed" },
            { date: "2026-02-19", action: "Triazole fungicide sprayed", status: "completed" },
            { date: "2026-02-23", action: "Follow-up monitoring", status: "completed" },
            { date: "2026-02-28", action: "Second follow-up", status: "pending" },
        ],
    },
    {
        id: "rpt-006",
        disease: "Fusarium Wilt",
        confidence: 0.89,
        severity: "Severe",
        treatment: "No direct chemical cure. Remove infected plants. Apply Trichoderma-based bio-fungicide to remaining soil.",
        follow_up: "Soil test after 14 days. Plan crop rotation for next season.",
        date: "2026-02-15",
        cropType: "Banana",
        imageUrl: "/images/fusarium-wilt.jpg",
        preventiveMeasures: [
            "Use tissue-cultured, disease-free planting material",
            "Implement strict quarantine for affected areas",
            "Add organic matter to improve soil health",
            "Use bio-control agents like Trichoderma",
        ],
        timeline: [
            { date: "2026-02-15", action: "Wilt symptoms identified", status: "completed" },
            { date: "2026-02-16", action: "Infected plants removed", status: "completed" },
            { date: "2026-02-17", action: "Bio-fungicide applied to soil", status: "completed" },
            { date: "2026-03-01", action: "Soil health test", status: "upcoming" },
        ],
    },
];
